dist: xenial

language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

install:
  - sudo apt-get update
  - . ./scripts/install_miniconda.sh
  - conda info -a
  - . ./scripts/create_testenv.sh
  - pip install coveralls pytest-cov

services:
  - xvfb

script:
  - travis_wait 30 py.test --pyargs bambi --cov-report term-missing --cov=bambi -v

after_success:
  - coveralls

before_cache:
# clean unused packages & installed files from conda cache
# this makes the cache rebuilt less frequently
  - conda clean --tarballs --packages --index-cache
  - rm -rf $HOME/miniconda/pkgs/cache

cache:
  directories:
    - $HOME/miniconda
